# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list = [10,20,30,40,50,60]
my_list

[10, 20, 30, 40, 50, 60]

In [3]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 30, 40, 50, 60])

In [4]:
type(x)

numpy.ndarray

In [5]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5,8],[9,13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [6]:
matrix2 = np.array([[4,6,8,7],[20,5,6,9]])
print(matrix2)
print(type(matrix2))

[[ 4  6  8  7]
 [20  5  6  9]]
<class 'numpy.ndarray'>


# 2. BUILT-IN METHODS AND FUNCTIONS 

In [7]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
print(x)

[0.73546518 0.46164036 0.31322519 0.82945805 0.10665528 0.53268529
 0.97442565 0.64623088 0.47688079 0.09613986 0.46022847 0.63348753
 0.86132022 0.98314194 0.14517276]


In [8]:
# you can create a matrix of random number as well
x=np.random.rand(5,5)
print(x)

[[0.44923701 0.84065682 0.17077709 0.53114813 0.03986427]
 [0.92942858 0.59562758 0.31354683 0.51192515 0.15175239]
 [0.79712807 0.72690238 0.20982639 0.55758614 0.89015762]
 [0.98870622 0.95798897 0.49617665 0.11847447 0.21418467]
 [0.45646165 0.05338598 0.49969524 0.43105892 0.12190472]]


In [9]:
# "randn()" normal distribution between 0 and 1
x =np.random.randn(10)
print(x)

[-2.32979272  0.20472637  3.02221615 -0.33611549 -0.12985201 -0.28881236
 -0.48124506  0.72281892  0.57379149  0.71444999]


In [10]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,10)
print(x)

5


In [11]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
print(x)

[ 7 25 38 11 81 79 50 87 48 20 30 41 26 26 84]


In [12]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [13]:
# Create an evenly spaced values with a step of 5
x = np.arange(1,50,5)
print(x)

[ 1  6 11 16 21 26 31 36 41 46]


In [14]:
# create a diagonal of ones and zeros everywhere else
x =np.eye(15)
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
# Array of ones
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
# Matrices of ones
x = np.ones((15,15))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
# Array of zeros
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [18]:
x= np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [19]:
x = int(input("Enter your number"))

y = np.random.randint(1,x,20)
print(y)

ValueError: invalid literal for int() with base 10: ''

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 
my_list=[-30,4,50,60,29,15,23,90]
print(my_list)
x = np.array(my_list)
print(x)


[-30, 4, 50, 60, 29, 15, 23, 90]
[-30   4  50  60  29  15  23  90]


In [ ]:
# Get Length of a numpy array
print(len(x))

8


In [ ]:
# Get shape
print(x.shape)

(8,)


In [ ]:
# Obtain the datatype
print(x.dtype)

int32


In [ ]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
print(z)

[[-30   4  50  60]
 [ 29  15  23  90]]


In [ ]:
# Obtain the maximum element (value)
x.max()


90

In [ ]:
# Obtain the minimum element (value)
x.min()

-30

In [ ]:
# Obtain the location of the max element
x.argmax()

7

In [ ]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300,500,10)
print(x)
z = x.reshape(4,5)
print(z)

[300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470
 480 490]
[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ 405 -443  661  874  635 -238  615  866  318  501 -289  139 -370  118
   258 -368 -747  878   81 -562]
 [ 237 -977  868 -699 -632 -364 -788 -591  179  944  -56 -885 -948 -136
   -33 -455  106 -245 -555  733]
 [-927  351  835 -826  528 -800 -193  420 -214 -193  333  864  647 -909
   -40 -848  253  978 -724  765]
 [-122  669 -677  788 -989  -78 -927 -709 -639  786 -901 -650 -985 -944
  -664 -441 -885  258  110  530]
 [ 272  754  458 -768  -25  339  828 -377  570 -229  647   74  585  752
   319  -86  408  -93 -351  -33]
 [-489  341  898  493 -809  142  648  873  825  359   16 -166  425 -232
  -838 -753 -602  149 -753  750]
 [-758 -206 -178 -303  395 -879 -105  482  116 -832  195 -984  -69  519
    96  105  519    7  412  721]
 [ 743 -638  804   82   48 -907  324 -942  441 -244  392 -352  190 -716
   109 -640 -732 -937 -433  191]
 [ 492 -409  101 -832  242  478 -768  398  286  129  638  858 -813  763
   848 -206  988 -742  206  418]
 [-123  807  949 -313 -998  953 -989 -847   62 -740  84

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1,10)

In [ ]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Add 2 numpy arrays together
sum = x+y

In [ ]:
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
squared =x**2

In [ ]:
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [ ]:
x = np.array([3,20,30])
y=np.array([4,6,7])

z =np.sqrt((x**2)+(y**2))
z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [21]:
import numpy as np
x = np.array([20,40,50,21,15])
x

array([20, 40, 50, 21, 15])

In [22]:
# Access specific index from the numpy array
x[0]

20

In [24]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:5]

array([20, 40, 50, 21, 15])

In [25]:
# Broadcasting, altering several values in a numpy array at once
x[0:2]=10

In [27]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(5,5))
matrix

array([[9, 5, 5, 4, 8],
       [5, 7, 9, 8, 2],
       [9, 7, 4, 1, 5],
       [2, 3, 7, 3, 7],
       [8, 8, 7, 5, 4]])

In [28]:
# Get a row from a mtrix
matrix[2]

array([9, 7, 4, 1, 5])

In [29]:
# Get one element
matrix[2][2]

4

In [30]:
mini_matrix = matrix[:3]

In [31]:
mini_matrix

array([[9, 5, 5, 4, 8],
       [5, 7, 9, 8, 2],
       [9, 7, 4, 1, 5]])

In [32]:
mini_matrix = matrix[:,2:]
mini_matrix

array([[5, 4, 8],
       [9, 8, 2],
       [4, 1, 5],
       [7, 3, 7],
       [7, 5, 4]])

In [33]:
mini_matrix=matrix[:,:2]
mini_matrix

array([[9, 5],
       [5, 7],
       [9, 7],
       [2, 3],
       [8, 8]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [38]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [43]:
X[4] = -1

In [44]:
print(X)

[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


In [46]:
X[:2,3:]=X[:2,3:]*2

In [47]:
print(X)

[[ 2 30 20 -4 -8]
 [ 3  4 40 -6 -4]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


# 6. ELEMENTS SELECTION (CONDITIONAL)

In [48]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[3, 3, 6, 7, 3],
       [4, 7, 7, 5, 8],
       [8, 8, 1, 8, 4],
       [6, 5, 1, 7, 8],
       [9, 8, 8, 9, 7]])

In [49]:
new_matrix = matrix[matrix>3]
new_matrix

array([6, 7, 4, 7, 7, 5, 8, 8, 8, 8, 4, 6, 5, 7, 8, 9, 8, 8, 9, 7])

In [50]:
new_matrix=matrix[matrix%2==0]
new_matrix

array([6, 4, 8, 8, 8, 8, 4, 6, 8, 8, 8])

In [51]:
new_matrix=matrix[matrix%2==1]
new_matrix

array([3, 3, 7, 3, 7, 7, 5, 1, 5, 1, 7, 9, 9, 7])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [53]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [55]:
X[X<0]=X[X<0]*0
print(X)

[[ 2 30 20  0  0]
 [ 3  4 40  0  0]
 [ 0  4  0 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]]


In [56]:
X[X%2==1]=25
print(X)

[[ 2 30 20  0  0]
 [25  4 40  0  0]
 [ 0  4  0 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X