# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list = [10,20,30,40,50,60]
my_list

[10, 20, 30, 40, 50, 60]

In [3]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 30, 40, 50, 60])

In [4]:
type(x)

numpy.ndarray

In [7]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5,8],[9,13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [12]:
matrix2 = np.array([[4,6,8,7],[20,5,6,9]])
print(matrix2)
print(type(matrix2))

[[ 4  6  8  7]
 [20  5  6  9]]
<class 'numpy.ndarray'>


# 2. BUILT-IN METHODS AND FUNCTIONS 

In [13]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
print(x)

[0.16667897 0.86935366 0.41131418 0.56413507 0.72472979 0.08389547
 0.399413   0.20472635 0.12961691 0.11521587 0.809887   0.33366328
 0.65249243 0.2258419  0.00933764]


In [14]:
# you can create a matrix of random number as well
x=np.random.rand(5,5)
print(x)

[[0.93035436 0.01347302 0.4746958  0.42340644 0.63068272]
 [0.99304272 0.52070477 0.1797422  0.54030224 0.50728206]
 [0.21176436 0.14065929 0.81575857 0.40128597 0.10660202]
 [0.01416663 0.5166612  0.42244556 0.47846496 0.05316796]
 [0.86256131 0.72566074 0.55908627 0.06995771 0.58350041]]


In [16]:
# "randn()" normal distribution between 0 and 1
x =np.random.randn(10)
print(x)

[ 2.05964377  0.72617378  1.96819368  0.22333393  0.25031175 -1.67635367
 -1.21838621  0.0478371  -0.22920286 -0.72724784]


In [17]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,10)
print(x)

2


In [18]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
print(x)

[78 88 56 72 23 30  2 75 99 59 59 92 23 73 76]


In [20]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [21]:
# Create an evenly spaced values with a step of 5
x = np.arange(1,50,5)
print(x)

[ 1  6 11 16 21 26 31 36 41 46]


In [23]:
# create a diagonal of ones and zeros everywhere else
x =np.eye(15)
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
# Array of ones
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
# Matrices of ones
x = np.ones((15,15))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
# Array of zeros
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [28]:
x= np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [37]:
x = int(input("Enter your number"))

y = np.random.randint(1,x,20)
print(y)

[9 6 3 3 7 3 6 6 4 3 6 7 1 5 2 3 7 1 4 5]


# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [38]:
# Let's define a one-dimensional array 
my_list=[-30,4,50,60,29,15,23,90]
print(my_list)
x = np.array(my_list)
print(x)


[-30, 4, 50, 60, 29, 15, 23, 90]
[-30   4  50  60  29  15  23  90]


In [39]:
# Get Length of a numpy array
print(len(x))

8


In [40]:
# Get shape
print(x.shape)

(8,)


In [42]:
# Obtain the datatype
print(x.dtype)

int32


In [44]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
print(z)

[[-30   4  50  60]
 [ 29  15  23  90]]


In [45]:
# Obtain the maximum element (value)
x.max()


90

In [46]:
# Obtain the minimum element (value)
x.min()

-30

In [47]:
# Obtain the location of the max element
x.argmax()

7

In [48]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [50]:
x = np.arange(300,500,10)
print(x)
z = x.reshape(4,5)
print(z)

[300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470
 480 490]
[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [54]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ 405 -443  661  874  635 -238  615  866  318  501 -289  139 -370  118
   258 -368 -747  878   81 -562]
 [ 237 -977  868 -699 -632 -364 -788 -591  179  944  -56 -885 -948 -136
   -33 -455  106 -245 -555  733]
 [-927  351  835 -826  528 -800 -193  420 -214 -193  333  864  647 -909
   -40 -848  253  978 -724  765]
 [-122  669 -677  788 -989  -78 -927 -709 -639  786 -901 -650 -985 -944
  -664 -441 -885  258  110  530]
 [ 272  754  458 -768  -25  339  828 -377  570 -229  647   74  585  752
   319  -86  408  -93 -351  -33]
 [-489  341  898  493 -809  142  648  873  825  359   16 -166  425 -232
  -838 -753 -602  149 -753  750]
 [-758 -206 -178 -303  395 -879 -105  482  116 -832  195 -984  -69  519
    96  105  519    7  412  721]
 [ 743 -638  804   82   48 -907  324 -942  441 -244  392 -352  190 -716
   109 -640 -732 -937 -433  191]
 [ 492 -409  101 -832  242  478 -768  398  286  129  638  858 -813  763
   848 -206  988 -742  206  418]
 [-123  807  949 -313 -998  953 -989 -847   62 -740  84

# 4. MATHEMATICAL OPERATIONS

In [55]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
y = np.arange(1,10)

In [57]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Add 2 numpy arrays together
sum = x+y

In [59]:
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
squared =x**2

In [61]:
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [65]:
x = np.array([3,20,30])
y=np.array([4,6,7])

z =np.sqrt((x**2)+(y**2))
z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [ ]:
# Access specific index from the numpy array


In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [ ]:
# Broadcasting, altering several values in a numpy array at once


In [ ]:
# Let's define a two dimensional numpy array


In [ ]:
# Get a row from a mtrix


In [ ]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X